version: '3.8'

services:
  app:
    build: .
    ports:
      - '3002:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - db_test
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: corserva
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME_TEST: corserva_test
      DB_HOST_TEST: db_test
      DB_PORT_TEST: 5432
    networks:
      - corserva-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corserva
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - corserva-network

  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corserva_test
    ports:
      - '5434:5432'
    volumes:
      - db_test_data:/var/lib/postgresql/data
    networks:
      - corserva-network

volumes:
  db_data:
  db_test_data:

networks:
  corserva-network:
